# Generated by Django 5.2.12 on 2026-04-06 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenantModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del Comercio (ej: Bar de Lalo)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "default_provider",
                    models.CharField(
                        choices=[
                            ("EXAMPLE", "Example Provider"),
                            ("INTERNAL", "Internal"),
                            ("TEST", "Test / Mock"),
                        ],
                        default="TEST",
                        help_text="Estrategia de delivery por defecto para este comercio",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="URL donde el comercio recibirá actualizaciones de estado",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "webhook_api_key",
                    models.CharField(
                        blank=True,
                        help_text="API Key que se enviará en el header X-API-Key al notificar al comercio",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants_tenant",
            },
        ),
    ]
