# Generated by Django 5.2.12 on 2026-04-06 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("couriers", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("email", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "shipments_location",
            },
        ),
        migrations.CreateModel(
            name="ShipmentModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference_id", models.CharField(max_length=100, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("EXAMPLE", "Example Provider"),
                            ("INTERNAL", "Internal"),
                            ("TEST", "Test / Mock"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("ASSIGNED", "Assigned"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tracking_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="couriers.couriermodel",
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments_as_destination",
                        to="shipments.locationmodel",
                    ),
                ),
                (
                    "origin_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments_as_origin",
                        to="shipments.locationmodel",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="tenants.tenantmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "db_table": "shipments_shipment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weight", models.FloatField(default=0, help_text="Weight in kg")),
                ("volume", models.FloatField(default=0, help_text="Volume in m³")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="shipments.shipmentmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package",
                "verbose_name_plural": "Packages",
                "db_table": "shipments_package",
            },
        ),
        migrations.CreateModel(
            name="ShipmentQuoteModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("EXAMPLE", "Example Provider"),
                            ("INTERNAL", "Internal"),
                            ("TEST", "Test / Mock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "destination_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes_as_destination",
                        to="shipments.locationmodel",
                    ),
                ),
                (
                    "origin_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes_as_origin",
                        to="shipments.locationmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Quote",
                "verbose_name_plural": "Shipment Quotes",
                "db_table": "shipments_shipment_quote",
            },
        ),
    ]
