# Generated by Django 5.2.12 on 2026-04-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
        ("tenants", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationmodel",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="tenants.tenantmodel",
            ),
        ),
    ]
