"""
Django settings for LogisticsCore project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from pathlib import Path
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", default="django-insecure-cal=t&rldtqnl=5v@m5-me)&n%y0#p@0_vd5%ssugxs0v1u8t^")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

_allowed_hosts = config("DJANGO_ALLOWED_HOSTS", default="*")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]

_csrf_origins = config("DJANGO_CSRF_TRUSTED_ORIGINS", default="")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()]

BASE_URL = config("BASE_URL", default="http://127.0.0.1:8000")
DELIVERY_API_KEY = config("DELIVERY_API_KEY", default="")

# ---- External Providers ----
# Configure your external provider keys here


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Domain apps
    "core",
    "shipments",
    "couriers",
    "tracking",
    "routing",
    "tenants",
    "providers",
    "web",
    "orders",
    "pricing",
    "dispatch",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "LogisticsCore.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "LogisticsCore.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {}

DATABASES["default"] = dj_database_url.config(
    default=config(
        "DATABASE_URL_CONNECTION", default="postgres://postgres:postgres@localhost:5432/LogisticsCore"
    ),
    conn_max_age=600,
    conn_health_checks=True,
)

# Celery
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TASK_TRACK_STARTED = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# S3

USE_S3 = os.getenv("USE_S3", "false").lower() == "true"

if USE_S3:
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
    AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL", "https://s3.amazonaws.com")
    AWS_DEFAULT_ACL = "public-read"
    AWS_QUERYSTRING_AUTH = False

    STORAGES = {
        "default": {"BACKEND": "core.storages.MediaStorage"},
        "staticfiles": {"BACKEND": "core.storages.StaticStorage"},
    }
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

    STATIC_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/static/"
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/"
else:
    STATIC_URL = "/static/"
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")



# Configuración del Panel de Control (Django Unfold)
UNFOLD = {
    "SITE_TITLE": "OpenDelivery",
    "SITE_HEADER": "Logistics Console",
    "SITE_URL": "/",
    
    # Agrupación y customización de Apps en Sidebar
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Logística Core",
                "separator": True, 
                "items": [
                    {"title": "Envíos", "link": "/admin/shipments/shipmentmodel/", "icon": "local_shipping"},
                    {"title": "Locaciones", "link": "/admin/shipments/locationmodel/", "icon": "location_on"},
                    {"title": "Paquetes", "link": "/admin/shipments/packagemodel/", "icon": "inventory_2"},
                    {"title": "Cotizaciones", "link": "/admin/shipments/shipmentquotemodel/", "icon": "request_quote"},
                ],
            },
            {
                "title": "Gestión de Flota",
                "separator": True,
                "items": [
                    {"title": "Couriers", "link": "/admin/couriers/couriermodel/", "icon": "sports_motorsports"},
                    {"title": "Vehículos", "link": "/admin/couriers/vehiclemodel/", "icon": "two_wheeler"},
                ],
            },
            {
                "title": "Rutas & Dispatching",
                "separator": True,
                "items": [
                    {"title": "Rutas", "link": "/admin/routing/routemodel/", "icon": "route"},
                    {"title": "Paradas", "link": "/admin/routing/stopmodel/", "icon": "pin_drop"},
                    {"title": "Tareas", "link": "/admin/routing/taskmodel/", "icon": "format_list_bulleted"},
                ],
            },
            {
                "title": "Trazabilidad",
                "separator": True,
                "items": [
                    {"title": "Eventos de Seguimiento", "link": "/admin/tracking/trackingeventmodel/", "icon": "timeline"},
                ],
            },
            {
                "title": _("Administración"),
                "icon": "settings",
                "items": [
                    {
                        "title": _("Comercios (Tenants)"),
                        "icon": "store",
                        "link": reverse_lazy("admin:tenants_tenantmodel_changelist"),
                    },
                ],
            },
        ],
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "shipments": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "providers": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
