# Generated by Django 5.2.12 on 2026-04-06 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=50)),
                (
                    "capacity_weight",
                    models.FloatField(default=0, help_text="Max weight in kg"),
                ),
                (
                    "capacity_volume",
                    models.FloatField(default=0, help_text="Max volume in m³"),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "couriers_vehicle",
            },
        ),
        migrations.CreateModel(
            name="CourierModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BUSY", "Busy"),
                            ("OFFLINE", "Offline"),
                        ],
                        default="OFFLINE",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courier",
                        to="couriers.vehiclemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Courier",
                "verbose_name_plural": "Couriers",
                "db_table": "couriers_courier",
            },
        ),
    ]
